name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  version:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: 🔻 Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: 🏷️ Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            @semantic-release/git
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pack & Publish Rapidata.MongoDB.Migrations
        if: ${{ steps.release.outputs.new_release_version }}
        run: |
          dotnet pack src/Rapidata.MongoDB.Migrations/Rapidata.MongoDB.Migrations.csproj --configuration Release --include-symbols --output ${{ github.workspace }}/output/Rapidata.MongoDB.Migrations
          dotnet nuget push ${{ github.workspace }}/output/Rapidata.MongoDB.Migrations/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s ${{ secrets.NUGET_PUSH_URL }}
        
      - name: Pack & Publish Rapidata.MongoDB.Migrations.AspNetCore
        if: ${{ steps.release.outputs.new_release_version }}
        run: |
          dotnet pack src/Rapidata.MongoDB.Migrations.AspNetCore/Rapidata.MongoDB.Migrations.AspNetCore.csproj --configuration Release --include-symbols --output ${{ github.workspace }}/output/Rapidata.MongoDB.Migrations.AspNetCore
          dotnet nuget push ${{ github.workspace }}/output/Rapidata.MongoDB.Migrations.AspNetCore/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s ${{ secrets.NUGET_PUSH_URL }}
